CC=g++
CFLAGS=-I.
DEPS = ElementaryParticle.h
OBJ = analyzer.o ElementaryParticle.o

%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)
analyzer: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)
clean:
	rm *.o	
	